name: hello-world
on: push
jobs:
    my-job:
        runs-on: ubuntu-latest
        steps:
            - name: my-step
              run: echo "Hello, world!"
on: pull_request
jobs:
    my-job:
        runs-on: ubuntu-latest
        steps:
            - name: my-step
              run: echo "Hello, pull-request!"